/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

 #ifndef _CREDENCIALES_H_RPCGEN
 #define _CREDENCIALES_H_RPCGEN
 
 #include <rpc/rpc.h>
 
 
 #ifdef __cplusplus
 extern "C" {
 #endif
 
 
 enum tipo_dato {
         ES_ENTERO = 0,
         ES_FLOTANTE = 1,
 };
 typedef enum tipo_dato tipo_dato;
 
 struct Dato {
         tipo_dato tipo;
         union {
                 int i;
                 float f;
                 char *s;
         } Dato_u;
 };
 typedef struct Dato Dato;
 
 #define UNION_AUTH_PROG 0x20000001
 #define UNION_AUTH_VERS 1
 
 #if defined(__STDC__) || defined(__cplusplus)
 #define PROCESAR 1
 extern  int * procesar_1(Dato *, CLIENT *);
 extern  int * procesar_1_svc(Dato *, struct svc_req *);
 extern int union_auth_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);
 
 #else /* K&R C */
 #define PROCESAR 1
 extern  int * procesar_1();
 extern  int * procesar_1_svc();
 extern int union_auth_prog_1_freeresult ();
 #endif /* K&R C */
 
 /* the xdr functions */
 
 #if defined(__STDC__) || defined(__cplusplus)
 extern  bool_t xdr_tipo_dato (XDR *, tipo_dato*);
 extern  bool_t xdr_Dato (XDR *, Dato*);
 
 #else /* K&R C */
 extern bool_t xdr_tipo_dato ();
 extern bool_t xdr_Dato ();
 
 #endif /* K&R C */
 
 #ifdef __cplusplus
 }
 #endif
 
 #endif /* !_CREDENCIALES_H_RPCGEN */