/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

 #include <memory.h> /* for memset */
 #include "credenciales.h"
 
 /* Default timeout can be changed using clnt_control() */
 static struct timeval TIMEOUT = { 25, 0 };
 
 int *
 procesar_1(Dato *argp, CLIENT *clnt)
 {
         static int clnt_res;
 
         memset((char *)&clnt_res, 0, sizeof(clnt_res));
         if (clnt_call (clnt, PROCESAR,
                 (xdrproc_t) xdr_Dato, (caddr_t) argp,
                 (xdrproc_t) xdr_int, (caddr_t) &clnt_res,
                 TIMEOUT) != RPC_SUCCESS) {
                 return (NULL);
         }
         return (&clnt_res);
 }