/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

 #include "credenciales.h"
 #include <stdio.h>
 #include <stdlib.h>
 
 void union_auth_prog_1(char *host) {
     CLIENT *clnt;
     int *result_1;
     Dato procesar_1_arg;
 
 #ifndef DEBUG
     clnt = clnt_create(host, UNION_AUTH_PROG, UNION_AUTH_VERS, "udp");
     if (clnt == NULL) {
         clnt_pcreateerror(host);
         exit(1);
     }

     // Configurar autenticación UNIX
     clnt->cl_auth = authunix_create_default();
     if (clnt->cl_auth == NULL) {
         fprintf(stderr, "Error al crear autenticación UNIX\n");
         clnt_destroy(clnt);
         exit(1);
     }
 #endif /* DEBUG */
 
     // Enviar un entero
     procesar_1_arg.tipo = ES_ENTERO;
     procesar_1_arg.Dato_u.i = 42; // Ejemplo de entero
     printf("Enviando entero: %d\n", procesar_1_arg.Dato_u.i);
 
     result_1 = procesar_1(&procesar_1_arg, clnt);
     if (result_1 == (int *)NULL) {
         clnt_perror(clnt, "Llamada fallida para entero");
     } else {
         printf("Resultado recibido del servidor (entero): %d\n", *result_1);
     }
 
     // Enviar un flotante
     procesar_1_arg.tipo = ES_FLOTANTE;
     procesar_1_arg.Dato_u.f = 3.14; // Ejemplo de flotante
     printf("Enviando flotante: %.2f\n", procesar_1_arg.Dato_u.f);
 
     result_1 = procesar_1(&procesar_1_arg, clnt);
     if (result_1 == (int *)NULL) {
         clnt_perror(clnt, "Llamada fallida para flotante");
     } else {
         printf("Resultado recibido del servidor (flotante): %d\n", *result_1);
     }
 
     // Enviar un mensaje (cadena)
     procesar_1_arg.tipo = -1; // Tipo por defecto
     procesar_1_arg.Dato_u.s = "Hola, servidor"; // Ejemplo de mensaje
     printf("Enviando mensaje: %s\n", procesar_1_arg.Dato_u.s);
 
     result_1 = procesar_1(&procesar_1_arg, clnt);
     if (result_1 == (int *)NULL) {
         clnt_perror(clnt, "Llamada fallida para mensaje");
     } else {
         printf("Resultado recibido del servidor (mensaje): %d\n", *result_1);
     }
 
 #ifndef DEBUG
     clnt_destroy(clnt);
 #endif /* DEBUG */
 }

 int main(int argc, char *argv[]) {
     if (argc < 2) {
         fprintf(stderr, "Uso: %s <host>\n", argv[0]);
         exit(1);
     }
     union_auth_prog_1(argv[1]);
     return 0;
 }