/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

 #include "credenciales.h"

 bool_t
 xdr_tipo_dato (XDR *xdrs, tipo_dato *objp)
 {
         register int32_t *buf;
 
          if (!xdr_enum (xdrs, (enum_t *) objp))
                  return FALSE;
         return TRUE;
 }
 
 bool_t
 xdr_Dato (XDR *xdrs, Dato *objp)
 {
         register int32_t *buf;
 
          if (!xdr_tipo_dato (xdrs, &objp->tipo))
                  return FALSE;
         switch (objp->tipo) {
         case ES_ENTERO:
                  if (!xdr_int (xdrs, &objp->Dato_u.i))
                          return FALSE;
                 break;
         case ES_FLOTANTE:
                  if (!xdr_float (xdrs, &objp->Dato_u.f))
                          return FALSE;
                 break;
         default:
                  if (!xdr_string (xdrs, &objp->Dato_u.s, ~0))
                          return FALSE;
                 break;
         }
         return TRUE;
 }