/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

 #ifndef _M_H_RPCGEN
 #define _M_H_RPCGEN
 
 #include <rpc/rpc.h>
 
 
 #ifdef __cplusplus
 extern "C" {
 #endif
 
 #define MAX_NAMELEN 255
 #define MAX_MUESTRAS 100
 #define NUM_SENSORES 3
 
 typedef char *NombreEstacion;
 
 enum TipoSensor {
         TEMPERATURA = 0,
         HUMEDAD = 1,
         PRESION = 2,
 };
 typedef enum TipoSensor TipoSensor;
 
 struct Sensor {
         TipoSensor tipo;
         struct {
                 u_int muestras_len;
                 float *muestras_val;
         } muestras;
 };
 typedef struct Sensor Sensor;
 
 struct Estacion {
         NombreEstacion nombre;
         Sensor sensores[NUM_SENSORES];
 };
 typedef struct Estacion Estacion;
 
 struct ConsultaSensor {
         NombreEstacion nombre;
         TipoSensor tipo;
 };
 typedef struct ConsultaSensor ConsultaSensor;
 
 struct Resultado1 {
         struct {
                 u_int valores_len;
                 float *valores_val;
         } valores;
 };
 typedef struct Resultado1 Resultado1;
 
 struct Resultado2 {
         float mediaTemperatura;
         float mediaHumedad;
         float mediaPresion;
 };
 typedef struct Resultado2 Resultado2;
 
 #define METEO_PROG 0x20000001
 #define VERS_GRUPO 1
 
 #if defined(__STDC__) || defined(__cplusplus)
 #define setEstacion 1
 extern  int * setestacion_1(NombreEstacion *, CLIENT *);
 extern  int * setestacion_1_svc(NombreEstacion *, struct svc_req *);
 #define getMediaSensor_Estacion 2
 extern  float * getmediasensor_estacion_1(ConsultaSensor *, CLIENT *);
 extern  float * getmediasensor_estacion_1_svc(ConsultaSensor *, struct svc_req *);
 #define getSensor_Estacion 3
 extern  Resultado1 * getsensor_estacion_1(ConsultaSensor *, CLIENT *);
 extern  Resultado1 * getsensor_estacion_1_svc(ConsultaSensor *, struct svc_req *);
 #define getMediasAllEstaciones 4
 extern  Resultado2 * getmediasallestaciones_1(void *, CLIENT *);
 extern  Resultado2 * getmediasallestaciones_1_svc(void *, struct svc_req *);
 #define darBaja 5
 extern  int * darbaja_1(void *, CLIENT *);
 extern  int * darbaja_1_svc(void *, struct svc_req *);
 extern int meteo_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);
 
 #else /* K&R C */
 #define setEstacion 1
 extern  int * setestacion_1();
 extern  int * setestacion_1_svc();
 #define getMediaSensor_Estacion 2
 extern  float * getmediasensor_estacion_1();
 extern  float * getmediasensor_estacion_1_svc();
 #define getSensor_Estacion 3
 extern  Resultado1 * getsensor_estacion_1();
 extern  Resultado1 * getsensor_estacion_1_svc();
 #define getMediasAllEstaciones 4
 extern  Resultado2 * getmediasallestaciones_1();
 extern  Resultado2 * getmediasallestaciones_1_svc();
 #define darBaja 5
 extern  int * darbaja_1();
 extern  int * darbaja_1_svc();
 extern int meteo_prog_1_freeresult ();
 #endif /* K&R C */
 
 /* the xdr functions */
 
 #if defined(__STDC__) || defined(__cplusplus)
 extern  bool_t xdr_NombreEstacion (XDR *, NombreEstacion*);
 extern  bool_t xdr_TipoSensor (XDR *, TipoSensor*);
 extern  bool_t xdr_Sensor (XDR *, Sensor*);
 extern  bool_t xdr_Estacion (XDR *, Estacion*);
 extern  bool_t xdr_ConsultaSensor (XDR *, ConsultaSensor*);
 extern  bool_t xdr_Resultado1 (XDR *, Resultado1*);
 extern  bool_t xdr_Resultado2 (XDR *, Resultado2*);
 
 #else /* K&R C */
 extern bool_t xdr_NombreEstacion ();
 extern bool_t xdr_TipoSensor ();
 extern bool_t xdr_Sensor ();
 extern bool_t xdr_Estacion ();
 extern bool_t xdr_ConsultaSensor ();
 extern bool_t xdr_Resultado1 ();
 extern bool_t xdr_Resultado2 ();
 
 #endif /* K&R C */
 
 #ifdef __cplusplus
 }
 #endif
 
 #endif /* !_M_H_RPCGEN */