/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

 #include <memory.h> /* for memset */
 #include "m.h"
 
 /* Default timeout can be changed using clnt_control() */
 static struct timeval TIMEOUT = { 25, 0 };
 
 int *
 setestacion_1(NombreEstacion *argp, CLIENT *clnt)
 {
         static int clnt_res;
 
         memset((char *)&clnt_res, 0, sizeof(clnt_res));
         if (clnt_call (clnt, setEstacion,
                 (xdrproc_t) xdr_NombreEstacion, (caddr_t) argp,
                 (xdrproc_t) xdr_int, (caddr_t) &clnt_res,
                 TIMEOUT) != RPC_SUCCESS) {
                 return (NULL);
         }
         return (&clnt_res);
 }
 
 float *
 getmediasensor_estacion_1(ConsultaSensor *argp, CLIENT *clnt)
 {
         static float clnt_res;
 
         memset((char *)&clnt_res, 0, sizeof(clnt_res));
         if (clnt_call (clnt, getMediaSensor_Estacion,
                 (xdrproc_t) xdr_ConsultaSensor, (caddr_t) argp,
                 (xdrproc_t) xdr_float, (caddr_t) &clnt_res,
                 TIMEOUT) != RPC_SUCCESS) {
                 return (NULL);
         }
         return (&clnt_res);
 }
 
 Resultado1 *
 getsensor_estacion_1(ConsultaSensor *argp, CLIENT *clnt)
 {
         static Resultado1 clnt_res;
 
         memset((char *)&clnt_res, 0, sizeof(clnt_res));
         if (clnt_call (clnt, getSensor_Estacion,
                 (xdrproc_t) xdr_ConsultaSensor, (caddr_t) argp,
                 (xdrproc_t) xdr_Resultado1, (caddr_t) &clnt_res,
                 TIMEOUT) != RPC_SUCCESS) {
                 return (NULL);
         }
         return (&clnt_res);
 }
 
 Resultado2 *
 getmediasallestaciones_1(void *argp, CLIENT *clnt)
 {
         static Resultado2 clnt_res;
 
         memset((char *)&clnt_res, 0, sizeof(clnt_res));
         if (clnt_call (clnt, getMediasAllEstaciones,
                 (xdrproc_t) xdr_void, (caddr_t) argp,
                 (xdrproc_t) xdr_Resultado2, (caddr_t) &clnt_res,
                 TIMEOUT) != RPC_SUCCESS) {
                 return (NULL);
         }
         return (&clnt_res);
 }
 
 int *
 darbaja_1(void *argp, CLIENT *clnt)
 {
         static int clnt_res;
 
         memset((char *)&clnt_res, 0, sizeof(clnt_res));
         if (clnt_call (clnt, darBaja,
                 (xdrproc_t) xdr_void, (caddr_t) argp,
                 (xdrproc_t) xdr_int, (caddr_t) &clnt_res,
                 TIMEOUT) != RPC_SUCCESS) {
                 return (NULL);
         }
         return (&clnt_res);
 }