/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

 #include "m.h"

 bool_t
 xdr_NombreEstacion (XDR *xdrs, NombreEstacion *objp)
 {
         register int32_t *buf;
 
          if (!xdr_string (xdrs, objp, MAX_NAMELEN))
                  return FALSE;
         return TRUE;
 }
 
 bool_t
 xdr_TipoSensor (XDR *xdrs, TipoSensor *objp)
 {
         register int32_t *buf;
 
          if (!xdr_enum (xdrs, (enum_t *) objp))
                  return FALSE;
         return TRUE;
 }
 
 bool_t
 xdr_Sensor (XDR *xdrs, Sensor *objp)
 {
         register int32_t *buf;
 
          if (!xdr_TipoSensor (xdrs, &objp->tipo))
                  return FALSE;
          if (!xdr_array (xdrs, (char **)&objp->muestras.muestras_val, (u_int *) &objp->muestras.muestras_len, MAX_MUESTR
 AS,
                 sizeof (float), (xdrproc_t) xdr_float))
                  return FALSE;
         return TRUE;
 }
 
 bool_t
 xdr_Estacion (XDR *xdrs, Estacion *objp)
 {
         register int32_t *buf;
 
         int i;
          if (!xdr_NombreEstacion (xdrs, &objp->nombre))
                  return FALSE;
          if (!xdr_vector (xdrs, (char *)objp->sensores, NUM_SENSORES,
                 sizeof (Sensor), (xdrproc_t) xdr_Sensor))
                  return FALSE;
         return TRUE;
 }
 
 bool_t
 xdr_ConsultaSensor (XDR *xdrs, ConsultaSensor *objp)
 {
         register int32_t *buf;
 
          if (!xdr_NombreEstacion (xdrs, &objp->nombre))
                  return FALSE;
          if (!xdr_TipoSensor (xdrs, &objp->tipo))
                  return FALSE;
         return TRUE;
 }
 
 bool_t
 xdr_Resultado1 (XDR *xdrs, Resultado1 *objp)
 {
         register int32_t *buf;
 
          if (!xdr_array (xdrs, (char **)&objp->valores.valores_val, (u_int *) &objp->valores.valores_len, MAX_MUESTRAS,
                 sizeof (float), (xdrproc_t) xdr_float))
                  return FALSE;
         return TRUE;
 }
 
 bool_t
 xdr_Resultado2 (XDR *xdrs, Resultado2 *objp)
 {
         register int32_t *buf;
 
          if (!xdr_float (xdrs, &objp->mediaTemperatura))
                  return FALSE;
          if (!xdr_float (xdrs, &objp->mediaHumedad))
                  return FALSE;
          if (!xdr_float (xdrs, &objp->mediaPresion))
                  return FALSE;
         return TRUE;
 }