/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

 #ifndef _CALCULADORA_H_RPCGEN
 #define _CALCULADORA_H_RPCGEN
 
 #include <rpc/rpc.h>
 
 
 #ifdef __cplusplus
 extern "C" {
 #endif
 
 
 struct datos {
         double dato1;
         double dato2;
 };
 typedef struct datos datos;
 
 #define CALCULADORA 0x20000001
 #define VERSION 1
 
 #if defined(__STDC__) || defined(__cplusplus)
 #define suma 1
 extern  double * suma_1(datos *, CLIENT *);
 extern  double * suma_1_svc(datos *, struct svc_req *);
 #define resta 2
 extern  double * resta_1(datos *, CLIENT *);
 extern  double * resta_1_svc(datos *, struct svc_req *);
 #define multiplicacion 3
 extern  double * multiplicacion_1(datos *, CLIENT *);
 extern  double * multiplicacion_1_svc(datos *, struct svc_req *);
 #define division 4
 extern  double * division_1(datos *, CLIENT *);
 extern  double * division_1_svc(datos *, struct svc_req *);
 #define potencia 5
 extern  double * potencia_1(datos *, CLIENT *);
 extern  double * potencia_1_svc(datos *, struct svc_req *);
 #define raiz 6
 extern  double * raiz_1(double *, CLIENT *);
 extern  double * raiz_1_svc(double *, struct svc_req *);
 #define n_llamadas 7
 extern  int * n_llamadas_1(void *, CLIENT *);
 extern  int * n_llamadas_1_svc(void *, struct svc_req *);
 #define menu 8
 extern  char * menu_1(void *, CLIENT *);
 extern  char * menu_1_svc(void *, struct svc_req *);
 extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);
 
 #else /* K&R C */
 #define suma 1
 extern  double * suma_1();
 extern  double * suma_1_svc();
 #define resta 2
 extern  double * resta_1();
 extern  double * resta_1_svc();
 #define multiplicacion 3
 extern  double * multiplicacion_1();
 extern  double * multiplicacion_1_svc();
 #define division 4
 extern  double * division_1();
 extern  double * division_1_svc();
 #define potencia 5
 extern  double * potencia_1();
 extern  double * potencia_1_svc();
 #define raiz 6
 extern  double * raiz_1();
 extern  double * raiz_1_svc();
 #define n_llamadas 7
 extern  int * n_llamadas_1();
 extern  int * n_llamadas_1_svc();
 #define menu 8
 extern  char * menu_1();
 extern  char * menu_1_svc();
 extern int calculadora_1_freeresult ();
 #endif /* K&R C */
 
 /* the xdr functions */
 
 #if defined(__STDC__) || defined(__cplusplus)
 extern  bool_t xdr_datos (XDR *, datos*);
 
 #else /* K&R C */
 extern bool_t xdr_datos ();
 
 #endif /* K&R C */
 
 #ifdef __cplusplus
 }
 #endif
 
 #endif /* !_CALCULADORA_H_RPCGEN */