/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>

void calculadora_1(char *host) {
    CLIENT *clnt;
    double *result;
    datos args;
    int *n_llamadas_result;
    char *menu_result;
    int option;
    double input;

#ifndef DEBUG
    clnt = clnt_create(host, CALCULADORA, VERSION, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */

    while (1) {
        menu_result = menu_1(NULL, clnt);
        if (menu_result == (char *)NULL) {
            clnt_perror(clnt, "Error fetching menu");
            break;
        }

        // Imprimimos el menú
        printf("%s\n", menu_result); 

        printf("Seleccione una opción 1-Suma;2-Resta;3-Mul;4-Div;5-Pow;6-Raiz;7-NumLlamada (0 para salir): ");
        scanf("%d", &option);

        if (option == 0) {
            printf("Saliendo...\n");
            break;
        }

        switch (option) {
            case 1: // Suma
                printf("Ingrese dos números para SUMA(separados por espacio): ");
                scanf("%lf %lf", &args.dato1, &args.dato2);
                result = suma_1(&args, clnt);
                break;
            case 2: // Resta
                printf("Ingrese dos números para RESTA(separados por espacio): ");
                scanf("%lf %lf", &args.dato1, &args.dato2);
                result = resta_1(&args, clnt);
                break;
            case 3: // Multiplicación
                printf("Ingrese dos números para MULTIPLICACION(separados por espacio): ");
                scanf("%lf %lf", &args.dato1, &args.dato2);
                result = multiplicacion_1(&args, clnt);
                break;
            case 4: // División
                printf("Ingrese dos números para DIVISION(separados por espacio): ");
                scanf("%lf %lf", &args.dato1, &args.dato2);
                result = division_1(&args, clnt);
                break;
            case 5: // Potencia
                printf("Ingrese la base y el exponente para POTENCIA (separados por espacio): ");
                scanf("%lf %lf", &args.dato1, &args.dato2);
                result = potencia_1(&args, clnt);
                break;
            case 6: // Raíz
                printf("Ingrese un número para RAIZ: ");
                scanf("%lf", &input);
                result = raiz_1(&input, clnt);
                break;
            case 7: // Número de llamadas
                n_llamadas_result = n_llamadas_1(NULL, clnt);
                if (n_llamadas_result == (int *)NULL) {
                    clnt_perror(clnt, "call failed");
                    continue;
                }
                printf("Número de llamadas realizadas: %d\n", *n_llamadas_result);
                continue;
            default:
                printf("Opción no válida. Intente de nuevo.\n");
                continue;
        }

        // Display result
        if (result == (double *)NULL) {
            clnt_perror(clnt, "call failed");
        } else {
            printf("Resultado: %lf\n", *result);
        }
    }

#ifndef DEBUG
    clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[]) {
    char *host;

    if (argc < 2) {
        printf("Uso: %s server_host\n", argv[0]);
        exit(1);
    }
    host = argv[1];
    calculadora_1(host);
    exit(0);
}

/*
En un sistema RPC (Remote Procedure Call) como este, los ficheros se distribuyen entre el servidor y el cliente de la siguiente manera:

En el servidor:
calculadora_server.c: Contiene la implementación de las funciones del servidor.
calculadora_svc.c: Contiene el código generado por rpcgen para manejar las solicitudes RPC.
calculadora_xdr.c: Contiene las funciones de serialización/deserialización (XDR).
calculadora.h: Contiene las definiciones compartidas entre cliente y servidor.
calculadora.x: Archivo fuente RPC que define las funciones y estructuras.
En el cliente:
calculadora_client.c: Contiene la lógica del cliente para interactuar con el servidor.
calculadora_clnt.c: Contiene el código generado por rpcgen para realizar las llamadas RPC.
calculadora_xdr.c: Contiene las funciones de serialización/deserialización (XDR).
calculadora.h: Contiene las definiciones compartidas entre cliente y servidor.
calculadora.x: Archivo fuente RPC que define las funciones y estructuras.
Resumen:
Archivos comunes (compartidos entre cliente y servidor): calculadora.h, calculadora.x, calculadora_xdr.c.
Archivos específicos del servidor: calculadora_server.c, calculadora_svc.c.
Archivos específicos del cliente: calculadora_client.c, calculadora_clnt.c.
*/