/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

 #include <memory.h> /* for memset */
 #include "calculadora.h"
 
 /* Default timeout can be changed using clnt_control() */
 static struct timeval TIMEOUT = { 25, 0 };
 
 double *
 suma_1(datos *argp, CLIENT *clnt)
 {
         static double clnt_res;
 
         memset((char *)&clnt_res, 0, sizeof(clnt_res));
         if (clnt_call (clnt, suma,
                 (xdrproc_t) xdr_datos, (caddr_t) argp,
                 (xdrproc_t) xdr_double, (caddr_t) &clnt_res,
                 TIMEOUT) != RPC_SUCCESS) {
                 return (NULL);
         }
         return (&clnt_res);
 }
 
 double *
 resta_1(datos *argp, CLIENT *clnt)
 {
         static double clnt_res;
 
         memset((char *)&clnt_res, 0, sizeof(clnt_res));
         if (clnt_call (clnt, resta,
                 (xdrproc_t) xdr_datos, (caddr_t) argp,
                 (xdrproc_t) xdr_double, (caddr_t) &clnt_res,
                 TIMEOUT) != RPC_SUCCESS) {
                 return (NULL);
         }
         return (&clnt_res);
 }
 
 double *
 multiplicacion_1(datos *argp, CLIENT *clnt)
 {
         static double clnt_res;
 
         memset((char *)&clnt_res, 0, sizeof(clnt_res));
         if (clnt_call (clnt, multiplicacion,
                 (xdrproc_t) xdr_datos, (caddr_t) argp,
                 (xdrproc_t) xdr_double, (caddr_t) &clnt_res,
                 TIMEOUT) != RPC_SUCCESS) {
                 return (NULL);
         }
         return (&clnt_res);
 }
 
 double *
 division_1(datos *argp, CLIENT *clnt)
 {
         static double clnt_res;
 
         memset((char *)&clnt_res, 0, sizeof(clnt_res));
         if (clnt_call (clnt, division,
                 (xdrproc_t) xdr_datos, (caddr_t) argp,
                 (xdrproc_t) xdr_double, (caddr_t) &clnt_res,
                 TIMEOUT) != RPC_SUCCESS) {
                 return (NULL);
         }
         return (&clnt_res);
 }
 
 double *
 potencia_1(datos *argp, CLIENT *clnt)
 {
         static double clnt_res;
 
         memset((char *)&clnt_res, 0, sizeof(clnt_res));
         if (clnt_call (clnt, potencia,
                 (xdrproc_t) xdr_datos, (caddr_t) argp,
                 (xdrproc_t) xdr_double, (caddr_t) &clnt_res,
                 TIMEOUT) != RPC_SUCCESS) {
                 return (NULL);
         }
         return (&clnt_res);
 }
 
 double *
 raiz_1(double *argp, CLIENT *clnt)
 {
         static double clnt_res;
 
         memset((char *)&clnt_res, 0, sizeof(clnt_res));
         if (clnt_call (clnt, raiz,
                 (xdrproc_t) xdr_double, (caddr_t) argp,
                 (xdrproc_t) xdr_double, (caddr_t) &clnt_res,
                 TIMEOUT) != RPC_SUCCESS) {
                 return (NULL);
         }
         return (&clnt_res);
 }
 
 int *
 n_llamadas_1(void *argp, CLIENT *clnt)
 {
         static int clnt_res;
 
         memset((char *)&clnt_res, 0, sizeof(clnt_res));
         if (clnt_call (clnt, n_llamadas,
                 (xdrproc_t) xdr_void, (caddr_t) argp,
                 (xdrproc_t) xdr_int, (caddr_t) &clnt_res,
                 TIMEOUT) != RPC_SUCCESS) {
                 return (NULL);
         }
         return (&clnt_res);
 }
 
 char *
 menu_1(void *argp, CLIENT *clnt)
 {
         static char clnt_res;
 
         memset((char *)&clnt_res, 0, sizeof(clnt_res));
         if (clnt_call (clnt, menu,
                 (xdrproc_t) xdr_void, (caddr_t) argp,
                 (xdrproc_t) xdr_char, (caddr_t) &clnt_res,
                 TIMEOUT) != RPC_SUCCESS) {
                 return (NULL);
         }
         return (&clnt_res);
 }