/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <math.h>

static int NUM_LLAMADAS=0;

double *
suma_1_svc(datos *argp, struct svc_req *rqstp)
{
        static double  result;

        /*
         * insert server code here
         */
        result=argp->dato1 + argp->dato2;
        NUM_LLAMADAS=NUM_LLAMADAS+1;
        return &result;
}

double *
resta_1_svc(datos *argp, struct svc_req *rqstp)
{
        static double  result;

        /*
         * insert server code here
         */
        result=argp->dato1 - argp->dato2;
        NUM_LLAMADAS=NUM_LLAMADAS+1;
        return &result;
}

double *
multiplicacion_1_svc(datos *argp, struct svc_req *rqstp)
{
        static double  result;

        /*
         * insert server code here
         */
        result=argp->dato1 * argp->dato2;
        NUM_LLAMADAS=NUM_LLAMADAS+1;
        return &result;
}

double *
division_1_svc(datos *argp, struct svc_req *rqstp)
{
        static double  result;

        /*
         * insert server code here
         */
         if (argp->dato2 != 0)
         {
             result = argp->dato1 / argp->dato2;
         }
         else
         {
             result = 0;
         }         NUM_LLAMADAS=NUM_LLAMADAS+1;
        return &result;
}

double *
potencia_1_svc(datos *argp, struct svc_req *rqstp)
{
        static double  result;

        /*
         * insert server code here
         */
        result = pow(argp->dato1, argp->dato2);
        NUM_LLAMADAS=NUM_LLAMADAS+1;
        return &result;
}

double *
raiz_1_svc(double *argp, struct svc_req *rqstp)
{
        static double  result;

        /*
         * insert server code here
         */
         if (*argp >= 0)
         {
             result = sqrt(*argp);
         }
         else
         {
             result = -1;
         }
        NUM_LLAMADAS=NUM_LLAMADAS+1;
        return &result;
}

int *
n_llamadas_1_svc(void *argp, struct svc_req *rqstp)
{
        static int  result;

        /*
         * insert server code here
         */
        result=NUM_LLAMADAS;
        return &result;
}

char *
menu_1_svc(void *argp, struct svc_req *rqstp)
{
    static char result[256]; // Buffer estático para evitar problemas de memoria

    // Formateamos el menú en el buffer
    snprintf(result, sizeof(result),
             "Menu:\n"
             "1. Suma\n"
             "2. Resta\n"
             "3. Multiplicacion\n"
             "4. Division\n"
             "5. Potencia\n"
             "6. Raiz\n"
             "7. Numero de llamadas\n"
             "0. Salir\n");

    // Aseguramos que la cadena esté terminada con '\0'
    result[sizeof(result) - 1] = '\0';

    return result;
}