/*
* Please do not edit this file.
* It was generated using rpcgen.
*/

#ifndef _DIRECTORIOS_H_RPCGEN
#define _DIRECTORIOS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNAMELEN 255

typedef char *nametype;

typedef struct namenode *namelist;

struct namenode {
       nametype name;
       namelist next;
};
typedef struct namenode namenode;

#define DIRECTORIOS 0x20000002
#define VERSIONB 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_directorios 1
extern  namelist * get_directorios_1(char **, CLIENT *);
extern  namelist * get_directorios_1_svc(char **, struct svc_req *);
extern int directorios_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_directorios 1
extern  namelist * get_directorios_1();
extern  namelist * get_directorios_1_svc();
extern int directorios_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nametype (XDR *, nametype*);
extern  bool_t xdr_namelist (XDR *, namelist*);
extern  bool_t xdr_namenode (XDR *, namenode*);

#else /* K&R C */
extern bool_t xdr_nametype ();
extern bool_t xdr_namelist ();
extern bool_t xdr_namenode ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DIRECTORIOS_H_RPCGEN */