/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "directorios.h"

// Función para imprimir los nombres de los archivos en el directorio
void imprimir_nombres(namelist *result) {
    namelist current = *result;
    while (current != NULL) {
        printf("%s\n", current->name);
        current = current->next;
    }
}

// Función para realizar la llamada RPC y manejar la respuesta
void obtener_directorios(CLIENT *clnt, char *dir) {
    namelist *result = get_directorios_1(&dir, clnt);
    if (result == (namelist *)NULL) {
        clnt_perror(clnt, "call failed");
    } else {
        imprimir_nombres(result);
    }
}

// Función principal del cliente
void directorios_1(char *host, char *dir) {
    CLIENT *clnt;

#ifndef DEBUG
    clnt = clnt_create(host, DIRECTORIOS, VERSIONB, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */

    obtener_directorios(clnt, dir);

#ifndef DEBUG
    clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[]) {
    if (argc < 3) {
        printf("usage: %s server_host directory_path\n", argv[0]);
        exit(1);
    }

    char *host = argv[1];
    char *directorio = argv[2];
    directorios_1(host, directorio);
    return 0;
}