/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

 #include <memory.h> /* for memset */
 #include "directorios.h"
 
 /* Default timeout can be changed using clnt_control() */
 static struct timeval TIMEOUT = { 25, 0 };
 
 namelist *
 get_directorios_1(char **argp, CLIENT *clnt)
 {
         static namelist clnt_res;
 
         memset((char *)&clnt_res, 0, sizeof(clnt_res));
         if (clnt_call (clnt, get_directorios,
                 (xdrproc_t) xdr_wrapstring, (caddr_t) argp,
                 (xdrproc_t) xdr_namelist, (caddr_t) &clnt_res,
                 TIMEOUT) != RPC_SUCCESS) {
                 return (NULL);
         }
         return (&clnt_res);
 }